### PR TITLE
Web support

### PR DESCRIPTION
**Pull request by r-oman-G**
Create `IWebSocket` interface with similar methods in dart:html and dart:io WebSocket. This is have not a big difference between. Test's work normally.  Trade-offs noticed: `dart:html WebSocket` should not use 'protocols' because in this case server will not response. And  `dart:html WebSocket`  should use `binaryType = 'arraybuffer';`

### CODE REVIEW

**Comment by FZambia** [comment]
@r-oman-G thanks, looks very promising! Could you please add a detailed pr description to describe things you done and maybe any trade-offs you noticed?

**Comment by r-oman-G** [comment]
@FZambia hi, thanks for fast answer. Update pull request

**Comment by FZambia** [comment]
> Trade-offs noticed: dart:html WebSocket should not use 'protocols' because in this case server will not response.

Did you find the underlying reason of this? Would be nice to use `centrifuge-protobuf` subprotocol to avoid using `?format=protobuf` in URL.

**Comment by r-oman-G** [comment]
> Did you find the underlying reason of this? Would be nice to use `centrifuge-protobuf` subprotocol to avoid using `?format=protobuf` in URL.
yes, if we do it when we create webSocket then server will not response. Or response something like this "server can't response, try again". I'm try it many times, but anywey `dart:html WebSockets` can't read our request, if we use protocol during creation WebSockets

> Also, plz run `dartfmt -w lib/ test/` as CI currently fails.
Okay, I we'll do it tomorrow

**Comment by FZambia** [comment]
> "server can't response, try again". I'm try it many times, but anywey dart:html WebSockets can't read our request, if we use protocol during creation WebSockets

On the server side you are using Centrifugo v2 right? Subprotocol only handled by Centrifugo v3 - maybe thats the reason.

**Comment by r-oman-G** [comment]
> > "server can't response, try again". I'm try it many times, but anywey dart:html WebSockets can't read our request, if we use protocol during creation WebSockets
> 
> On the server side you are using Centrifugo v2 right? Subprotocol only handled by Centrifugo v3 - maybe thats the reason.

maybe you right, cause i'm test centrifugo only with one server

**Comment by FZambia** [comment]
> Also, plz run dartfmt -w lib/ test/ as CI currently fails.

Still actual. @r-oman-G are you still interested in getting this merged?

**Comment by r-oman-G** [comment]
yts i will. Sorry for that, I have no time.
I will try try it in next week

вс, 19 сент. 2021 г. в 11:45, Alexander Emelin ***@***.***>:

**Comment by FZambia** [comment]
Thx, no rush - just wanted to understand the status.

**Comment by adimshev** [comment]
Any updates?

**Comment by FZambia** [comment]
This is still awesome to have, but needs to be addressed over latest version of SDK. So whether this PR should be updated or a new one created.

**Comment by FZambia** [comment]
Closing in favour of #73

**Pull request closed without merging**
