### PR TITLE
Async methods fix

### LINKED ISSUE #31: Make all async functions return a Future
Would it be possible to return a future for all async methods? I have noticed that some async methods return `void` and not `Future<void>` which make then non awaitable. Is this on purpose?

Ex: I would like to await `connect` but  can't because it does not return a future:

```dart
@override
  void connect() async {
    return _connect();
  }
```

Here `_connect` returns a future, and `connect` would be great this way:

 ```dart
  Future<void> connect() async {
    return await _connect();
  }
// or the short way
  Future<void> connect() async => _connect();
```

Is it possible or the actual way is by design?

### PR DESCRIPTION
**Pull request by vanelizarov**
Fixes #31

### CODE REVIEW

**Comment by LevinGermann** [comment]
Hi @vanelizarov 
I don't see this merged to master, why has this been closed? I thought it would be a welcome change.

**Comment by vanelizarov** [comment]
@LevinGermann hello! I've messed up updating my fork, will submit another PR a little bit later 🙂

**Comment by LevinGermann** [comment]
@vanelizarov Ah, got you. Thank you very much! 😊

**Comment by vanelizarov** [comment]
> @vanelizarov Ah, got you. Thank you very much! 😊

Fixed in #42

**Pull request closed without merging**
